baseURL = "https://swarnendu-stat.netlify.app/"
title = "Welcome to My R Blog"
theme = "hugo-theme-stack"

[module.hugoVersion]
    min = "0.146.7"

[outputs]
  home = ["html", "rss"]
  section = ["html", "rss"]
  taxonomy = ["html", "rss"]
  term = ["html", "rss"]
  
[params]
  mainSections = ["post"]
  customHead = '''
    <meta name="google-site-verification" content="QLHWz1H9o5x-4F4pUJu_Cy2gHT1O-jJz_xpdEBu69nM" />
  '''
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "index"

[permalinks]
  post = "/:year/:month/:slug/"

[params.feed]
  enable = true
  limit = 20
  sections = ["post"]
  
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
  
disableKinds = ["sitemap"]  