theme = "hugo-theme-stack"
[module.hugoVersion]
min = "0.128.0"
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  
