baseURL = "https://swarnendu-stat.netlify.app/"
title = "Welcome to My R Blog"
theme = "hugo-theme-stack"
[module.hugoVersion]
min = "0.128.0"
[outputs]
  home = ["html", "rss"]
  section = ["html", "rss"]
  taxonomy = ["html", "rss"]
  term = ["html", "rss"]
  
[params]
  mainSections = ["post"]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "index"

[permalinks]
  post = "/:year/:month/:slug/"

[params.feed]
  enable = true
  limit = 20
  sections = ["post"]