baseurl: /
languageCode: en-US
title: "Statistically Speaking: An R Journey"
theme: "hugo-book"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /post/:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/swarnendu-stat/bnns
    - name: R-bloggers
    - url: http://www.r-bloggers.com
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  home_layout: "static"  
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
